---
- name: Update
  apt:
    upgrade: dist
    cache_valid_time: 3600

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common utilities
  apt:
    pkg:
      - htop
      - git
      - python3.8
      - python3-dev
      - python3.8-venv
      - python3-venv

- name: Add ssh keys
  blockinfile:
    block: "{{ lookup('file', './ssh_keys/authorized_keys') }}"
    dest: /home/ubuntu/.ssh/authorized_keys
    backup: yes
    
## set up java runtime for later installing kinesis agent
- name: Install Java DK for kinesis agent installation
  become: yes
  apt:
    pkg:
      - openjdk-8-jdk
