---
# Reference: https://github.com/libre-ops/metabase/tree/master/tasks

# [OPTIONAL FOR DEV PHASE] Create user groups
- name: create group
  group:
    name: "{{ metabase_group }}"
  become: yes

- name: create metabase user
  user:
    name: "{{ metabase_user }}"
    group: "{{ metabase_group }}"
  become: yes

# Install app

- name: create log dir
  file:
    path: "{{ metabase_log_dir }}"
    state: directory
    mode: 0744
    owner: "{{ metabase_user }}"
    group: "{{ metabase_group }}"
  become: yes

- name: create app dir
  file:
    path: "{{ metabase_app_dir }}/{{ metabase_version }}"
    state: directory
    mode: 0750
    owner: root
    group: "{{ metabase_group }}"
  become: yes

- name: download metabase
  get_url:
    url: "https://downloads.metabase.com/{{ metabase_version }}/metabase.jar"
    dest: "{{ metabase_jarfile }}"
    owner: root
    group: "{{ metabase_group }}"
    mode: 0750
  become: yes

- name: add logging config
  template:
    src: log4j.j2
    dest: "{{ metabase_working_directory }}/log4j.properties"
    owner: "{{ metabase_user }}"
    group: "{{ metabase_group }}"
    mode: 0640
  become: yes

- name: add metabase service
  template:
    src: metabase_service.j2
    dest: /etc/systemd/system/metabase.service
    mode: 0750
  become: yes
  notify:
    - reload systemd
    - restart metabase
    - remove old versions

- name: enable metabase service
  service:
    name: metabase
    state: started
    enabled: yes

- name: flush handlers
  meta: flush_handlers

# Configure metabase

- name: ensure metabase has started (this can take a while...)
  uri:
    url: "http://{{ metabase_host }}:{{ metabase_port }}/api/session/properties"
    status_code: 200
  register: metabase_api_session
  until: metabase_api_session is not failed
  retries: 10
  delay: 6

- name: submit initial configuration
  uri:
    url: "http://{{ metabase_host }}:{{ metabase_port }}/api/setup"
    method: POST
    body:
      token: "{{ metabase_api_session.json['setup-token'] }}"
      user:
        first_name: "{{ metabase_admin.first_name }}"
        last_name: "{{ metabase_admin.last_name }}"
        email: "{{ metabase_admin.email }}"
        password: "{{ metabase_admin.password }}"
      prefs:
        site_name: "{{ metabase_prefs.site_name }}"
        allow_tracking: "{{ metabase_prefs.allow_tracking }}"
    body_format: json
    status_code: 200
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
  register: metabase_api_setup
  when: metabase_api_session.json["setup-token"]

- name: create initial databases
  include_tasks: add_database.yml
  vars:
    metabase_session: "{{ metabase_api_setup }}"
  loop: "{{ metabase_databases }}"
  loop_control:
    loop_var: database_item
  when: metabase_api_session.json["setup-token"]

- name: Copy nginx app server block
become: yes
template:
  src: edu-flask-app.conf
  dest: /etc/nginx/conf.d/metabase_server.conf
notify: reload nginx
