---

- name: Install Java runtime for digdag
  become: yes
  apt:
    pkg:
      - openjdk-8-jre

- name: Get digdag package
  become: yes
  get_url:
    url: "https://dl.digdag.io/digdag-latest"        
    dest: /usr/local/bin/digdag
    mode: a+x

- name: copy database config
  become: yes
  template:
    src: digdag.properties
    dest: /etc/digdag.properties

- name: copy digdag systemd service config 
  become: yes
  template:
    src: .service
    dest: /etc/systemd/system/digdag.service   

- name: start systemd app service
  become: yes
  systemd: name=digdag state=restarted enabled=yes

- name: Copy nginx app server block
  become: yes
  template:
    src: digdag-app.conf
    dest: /etc/nginx/conf.d/digdag-app.conf
  notify: reload nginx