---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

- name: add certbot repository
  apt_repository:
    repo: ppa:certbot/certbot

- name: Copy nginx configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: apt update cache
  apt:
    update_cache: yes

- name: Install certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

### WARNING, TODO: FIND A WAY TO REUSE OLD CERTIFICATE 
### BECAUSE YOU WILL NOT ABLE TO GENERATE NEW ONE 5 TIMES A WEEK
- name: install certbot certificates and auto-renewal
  shell: certbot --nginx -m {{ ssl_email }} --agree-tos -d {{ domain_name }} --non-interactive

- name: Ensures site dir exists
  file:
    path: /var/www/{{ domain_name }}
    state: directory

- name: Copy sample index file
  template:
    src: index.html
    dest: /var/www/{{ domain_name }}/index.html
  notify: reload nginx

- meta: flush_handlers